image: maven:latest

stages:
  - pages

cache:
  paths:
    - /root/.m2/repository/

pages:
  stage: pages
  script:
    - mvn javadoc:javadoc
  artifacts:
    paths:
      - public
  only:
    - master
